// Code generated by tetratelabs/protoc-gen-cobra.
// source: nosvc/nosvc.proto
// DO NOT EDIT!

/*
Package nosvc is a generated protocol buffer package.

It is generated from these files:
	nosvc/nosvc.proto

It has these top-level commands:
*/

package nosvc

import (
	proto "github.com/golang/protobuf/proto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
