version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
executors:
  build:
    docker:
      - image: circleci/golang:1.13.1
    working_directory: ~/src

jobs:
  build:
    executor: build
    steps:
      - checkout
      - run: ./ci/install-protoc.sh
      - run: GOPROXY=https://proxy.golang.org go mod download
      - run: go build -o protoc-gen-cobra main.go
      - run: go test -v
